/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagedelivery.FrontEnd.CheckIn;

import java.sql.Connection;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import packagedelivery.DBmanagers.ClientDBManager;
import packagedelivery.DummyClasses.Client;

/**
 *
 * @author zofia
 */
public class ClientNitDialog extends javax.swing.JDialog {
    private Connection connection;
    private ClientDBManager clientManager;
    private ClientInfoDialog information;
    /**
     * Creates new form ClientInfoDialog
     */
    public ClientNitDialog(boolean modal, Connection connection) {
        initComponents();
        this.setModal(modal);
        this.connection = connection;
        clientManager = new ClientDBManager(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nitField = new javax.swing.JTextField();
        nitLabel = new javax.swing.JLabel();
        facturarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nitLabel.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        nitLabel.setForeground(new java.awt.Color(153, 0, 51));
        nitLabel.setText("Ingrese Nit:");

        facturarButton.setBackground(new java.awt.Color(153, 0, 51));
        facturarButton.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        facturarButton.setForeground(new java.awt.Color(204, 204, 204));
        facturarButton.setText("Aceptar");
        facturarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facturarButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nitLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nitField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nitLabel))
                .addGap(18, 18, 18)
                .addComponent(facturarButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facturarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarButtonActionPerformed
        // TODO add your handling code here:
        if(nitField.getText().isEmpty()) { //SEGUIR AQUI MANDAR DATOS A PACKAGEFRAME
            JOptionPane.showMessageDialog(this, "Ingrese NIT", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Client client = clientManager.getClienInList(nitField.getText());
             if(client == null) {
                 information = new ClientInfoDialog(true, connection, null);                 
                 this.information.setVisible(true);
                 getData();
                 this.setVisible(false);
             } else {
                 information = new ClientInfoDialog(true, connection, client);
                 this.information.setVisible(true);
                 getData();
                 this.setVisible(false);
             }
        }

    }//GEN-LAST:event_facturarButtonActionPerformed

   public String getData() {
       String nit = this.information.getNit();
       return nit;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton facturarButton;
    private javax.swing.JTextField nitField;
    private javax.swing.JLabel nitLabel;
    // End of variables declaration//GEN-END:variables
}
