/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagedelivery.FrontEnd.CheckIn;

import java.sql.Connection;
import packagedelivery.DummyClasses.User;
import packagedelivery.FrontEnd.LogInDialog;

/**
 *
 * @author zofia
 */
public class ReceptionistFrame extends javax.swing.JFrame {

    private Connection connection;
    private PackageFrame packageFrame;
    /**
     * Creates new form ReceptionistFrame
     */
    public ReceptionistFrame(User user, Connection connection) {
        packageFrame = new PackageFrame(connection);
        initComponents();
        this.connection = connection;
        this.desktopPane.add(packageFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        packageMenu = new javax.swing.JMenu();
        newPackageItem = new javax.swing.JMenuItem();
        locationItem = new javax.swing.JMenuItem();
        clientMenu = new javax.swing.JMenu();
        clientListItem = new javax.swing.JMenuItem();
        otherMenu = new javax.swing.JMenu();
        logoutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reception");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        packageMenu.setText("Paquetes");

        newPackageItem.setText("Ingreso de paquetes");
        newPackageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPackageItemActionPerformed(evt);
            }
        });
        packageMenu.add(newPackageItem);

        locationItem.setText("Localizacion");
        packageMenu.add(locationItem);

        menuBar.add(packageMenu);

        clientMenu.setText("Clientes");

        clientListItem.setText("Listado de Clientes");
        clientListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientListItemActionPerformed(evt);
            }
        });
        clientMenu.add(clientListItem);

        menuBar.add(clientMenu);

        otherMenu.setText("Otros");

        logoutItem.setText("Cerrar Sesion");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        otherMenu.add(logoutItem);

        menuBar.add(otherMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPackageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPackageItemActionPerformed
        // TODO add your handling code here:
        this.packageFrame.setVisible(true);
        this.packageFrame.setComboModel();
        this.packageFrame.getRate();
    }//GEN-LAST:event_newPackageItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LogInDialog login = new LogInDialog(true, connection);
        login.setVisible(true);
    }//GEN-LAST:event_logoutItemActionPerformed

    private void clientListItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientListItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientListItemActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clientListItem;
    private javax.swing.JMenu clientMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem locationItem;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newPackageItem;
    private javax.swing.JMenu otherMenu;
    private javax.swing.JMenu packageMenu;
    // End of variables declaration//GEN-END:variables
}
