/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagedelivery.FrontEnd.Management;

import java.sql.Connection;
import packagedelivery.DummyClasses.User;
import packagedelivery.FrontEnd.LogInDialog;

/**
 *
 * @author zofia
 */
public class ManagementFrame extends javax.swing.JFrame {
    private Connection connection;
    private UsersFrame userFrame;
    private DestinationFrame destinationFrame;
    /**
     * Creates new form ManagementFrame
     */
    public ManagementFrame(User user, Connection connection) {
        userFrame = new UsersFrame(connection);
        destinationFrame = new DestinationFrame(connection);
        initComponents();
        this.connection = connection;
        this.desktopPane.add(userFrame);
        this.desktopPane.add(destinationFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        routeMenu = new javax.swing.JMenu();
        userItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        destinationMenu = new javax.swing.JMenuItem();
        checkpointMenu = new javax.swing.JMenu();
        ReportesMenu = new javax.swing.JMenu();
        otherMenu = new javax.swing.JMenu();
        logoutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1239, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        routeMenu.setText("Registros");

        userItem.setText("Usuario");
        userItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userItemActionPerformed(evt);
            }
        });
        routeMenu.add(userItem);

        jMenuItem1.setText("Ruta");
        routeMenu.add(jMenuItem1);

        destinationMenu.setText("Destino");
        destinationMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationMenuActionPerformed(evt);
            }
        });
        routeMenu.add(destinationMenu);

        menuBar.add(routeMenu);

        checkpointMenu.setText("Checkpoint");
        menuBar.add(checkpointMenu);

        ReportesMenu.setText("Reportes");
        menuBar.add(ReportesMenu);

        otherMenu.setText("Otros");

        logoutItem.setText("Cerrar Sesion");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        otherMenu.add(logoutItem);

        menuBar.add(otherMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userItemActionPerformed
        // TODO add your handling code here:
        userFrame.setVisible(true);
    }//GEN-LAST:event_userItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LogInDialog login = new LogInDialog(true, this.connection);
        login.setVisible(true);
    }//GEN-LAST:event_logoutItemActionPerformed

    private void destinationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationMenuActionPerformed
        // TODO add your handling code here:
        destinationFrame.setVisible(true);
    }//GEN-LAST:event_destinationMenuActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ReportesMenu;
    private javax.swing.JMenu checkpointMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem destinationMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu otherMenu;
    private javax.swing.JMenu routeMenu;
    private javax.swing.JMenuItem userItem;
    // End of variables declaration//GEN-END:variables
}
