/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagedelivery.FrontEnd.Management;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import packagedelivery.DBmanagers.DBManager;
import packagedelivery.DBmanagers.DestinationDBManager;
import packagedelivery.DBmanagers.RouteDBManager;
import packagedelivery.DummyClasses.Destination;
import packagedelivery.DummyClasses.Route;

/**
 *
 * @author zofia
 */
public class RoutesFrame extends javax.swing.JInternalFrame {
    private Connection connection;
    private Route route;
    private List<Route> routes;
    private List<Destination> destinations;
    private ObservableList<Route> observableRoutes;
    private DBManager manager;
    private RouteDBManager routeManager;
    private DestinationDBManager destinationManager;
    private static final String DESACTIVATE_QUERY = "UPDATE Route SET Disabled = 1 WHERE IdRoute = ";
    private static final String DESTINATION_QUERY = "SELECT * FROM Destination;";
    private static final String GENERAL_QUERY = "SELECT * FROM Route;";
    private static final String ASC_BY_DESTINATION_QUERY = "SELECT * FROM Route ORDER BY Destination_Id ASC";
    private static final String DESC_BY_DESTINATION_QUERY = "SELECT * FROM Route ORDER BY Destination_Id DESC";
    private static final String SELECTION = "SELECT * FROM Route ORDER BY ";
    /**
     * Creates new form RoutesFrame
     */
    public RoutesFrame(Connection connection) {
        destinations = new ArrayList<>();
        routes = new ArrayList<>();
        observableRoutes = ObservableCollections.observableList(routes);
        initComponents();
        this.connection = connection;
        routeManager = new RouteDBManager(connection);
        manager = new DBManager(connection);
        destinationManager = new DestinationDBManager(connection);
        refreshObservableList(routeManager.getRoutes(GENERAL_QUERY));
        setComboModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        searchingText = new javax.swing.JLabel();
        elementText = new javax.swing.JLabel();
        searchingComboBox = new javax.swing.JComboBox<>();
        orderComboBox = new javax.swing.JComboBox<>();
        searchingButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        routesPanel = new javax.swing.JTabbedPane();
        tablePanel = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        desactivateButton = new javax.swing.JButton();
        informationLabel = new javax.swing.JLabel();
        createPanel = new javax.swing.JPanel();
        creatStuffPanel = new javax.swing.JPanel();
        idField = new javax.swing.JTextField();
        nameText = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        userText = new javax.swing.JLabel();
        destinationComboBox = new javax.swing.JComboBox<>();
        orderText = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rutas");

        searchingText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        searchingText.setForeground(new java.awt.Color(0, 51, 102));
        searchingText.setText("Busqueda Personalizada--------------------------------------------------------------------");

        elementText.setText("Por Elemento:");

        searchingComboBox.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        searchingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---vacio---", "IdRoute", "Destination_Id", "Disabled", "PackagesInRoute", " " }));

        orderComboBox.setForeground(new java.awt.Color(153, 153, 153));
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-vacio-", "ASC", "DESC" }));

        searchingButton.setBackground(new java.awt.Color(153, 153, 153));
        searchingButton.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        searchingButton.setForeground(new java.awt.Color(102, 102, 102));
        searchingButton.setText("Buscar");
        searchingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingButtonActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${observableRoutes}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, table);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${routeId}"));
        columnBinding.setColumnName("Route Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${destinationId}"));
        columnBinding.setColumnName("Destination Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${packagesInRoute}"));
        columnBinding.setColumnName("Packages In Route");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${disabled}"));
        columnBinding.setColumnName("Disabled");
        columnBinding.setColumnClass(Boolean.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        scrollPanel.setViewportView(table);

        desactivateButton.setBackground(new java.awt.Color(153, 153, 153));
        desactivateButton.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        desactivateButton.setForeground(new java.awt.Color(102, 102, 102));
        desactivateButton.setText("Desactivar");
        desactivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivateButtonActionPerformed(evt);
            }
        });

        informationLabel.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        informationLabel.setForeground(new java.awt.Color(0, 51, 102));
        informationLabel.setText("Seleccione una fila -----------------------------------------");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addComponent(informationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desactivateButton)))
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desactivateButton)
                    .addComponent(informationLabel))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        routesPanel.addTab("Rutas", tablePanel);

        creatStuffPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 51, 102));
        nameText.setText("Destino:");

        createButton.setBackground(new java.awt.Color(153, 153, 153));
        createButton.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        createButton.setForeground(new java.awt.Color(102, 102, 102));
        createButton.setText("Crear");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        userText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        userText.setForeground(new java.awt.Color(0, 51, 102));
        userText.setText("ID:");

        destinationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout creatStuffPanelLayout = new javax.swing.GroupLayout(creatStuffPanel);
        creatStuffPanel.setLayout(creatStuffPanelLayout);
        creatStuffPanelLayout.setHorizontalGroup(
            creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatStuffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userText, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(41, 41, 41)
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idField)
                    .addComponent(destinationComboBox, 0, 268, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatStuffPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        creatStuffPanelLayout.setVerticalGroup(
            creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatStuffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText)
                    .addComponent(destinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(createButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(creatStuffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(creatStuffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        routesPanel.addTab("Crear Ruta", createPanel);

        orderText.setText("Orden:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(elementText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(orderText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(separator)
                                .addComponent(routesPanel)))
                        .addComponent(searchingText))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elementText)
                    .addComponent(orderText)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchingButton))
                .addContainerGap(612, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(searchingText)
                    .addGap(47, 47, 47)
                    .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(routesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingButtonActionPerformed
        // TODO add your handling code here:
        if(searchingComboBox.getModel().getSelectedItem().equals("---vacio---") &&
            !orderComboBox.getModel().getSelectedItem().equals("-vacio-")) {
            if(orderComboBox.getModel().getSelectedItem().equals("ASC")) {
                refreshObservableList(routeManager.getRoutes(ASC_BY_DESTINATION_QUERY));
            } else {
                refreshObservableList(routeManager.getRoutes(DESC_BY_DESTINATION_QUERY));
            }
        } else if(!searchingComboBox.getModel().getSelectedItem().equals("---vacio---")
            && !orderComboBox.getModel().getSelectedItem().equals("-vacio-")) {
            String data = searchingComboBox.getModel().getSelectedItem().toString();
            String order = orderComboBox.getModel().getSelectedItem().toString();
            String query = SELECTION + data + " " +order;
            refreshObservableList(routeManager.getRoutes(query));
        } else if(searchingComboBox.getModel().getSelectedItem().equals("---vacio---") &&
                orderComboBox.getModel().getSelectedItem().equals("-vacio-")) {
            refreshObservableList(routeManager.getRoutes(GENERAL_QUERY));
        }
    }//GEN-LAST:event_searchingButtonActionPerformed

    private void desactivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivateButtonActionPerformed
//         TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila...", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            getSelectedRoute(selectedRow);
            if(this.route.getPackagesInRoute() == 0) {
                desactivateSelectedRoute(selectedRow);
                refreshObservableList(routeManager.getRoutes(GENERAL_QUERY));
                JOptionPane.showMessageDialog(this, "Ruta desactivada con exito!", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se puede desactivar dicha ruta, ya que contiene paquetes.",
                        "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }           
        }
    }//GEN-LAST:event_desactivateButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(idField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los campos...", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                routeManager.addRoute(idField.getText(), 
                        destinationComboBox.getModel().getSelectedItem().toString(), true, false, 0);
                cleanFields();
                JOptionPane.showMessageDialog(this, "Ruta creada con exito...", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                refreshObservableList(routeManager.getRoutes(GENERAL_QUERY));
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_createButtonActionPerformed

    public void getSelectedRoute(int selectedRow) {
        String selectedRoute = table.getModel().getValueAt(selectedRow, 0).toString();
        this.route = routeManager.getRouteInList(selectedRoute);
    }
    public void desactivateSelectedRoute(int selectedRow) {
        String selectedRoute = table.getModel().getValueAt(selectedRow, 0).toString();
        String query = DESACTIVATE_QUERY + "'"+selectedRoute+"';";
        manager.updateElement(query);
    }
    
    public void cleanFields() {
        idField.setText("");
        setComboModel();
    }
    
    public void setComboModel() {
        this.destinations = destinationManager.getElements(DESTINATION_QUERY);
        Vector destinationId = new Vector();
        Destination destination;
        for (int i = 0; i < this.destinations.size(); i++) {
            destination = this.destinations.get(i);            
            destinationId.add(destination.getDestinationId());
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(destinationId);
        destinationComboBox.setModel(model);
    }
    
    public void refreshObservableList(List<Route> list) {
        this.observableRoutes.clear();
        this.observableRoutes.addAll(list);
    }
    
    public ObservableList<Route> getObservableRoutes() {
        return observableRoutes;
    }

    public void setObservableRoutes(ObservableList<Route> observableRoutes) {
        this.observableRoutes = observableRoutes;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel creatStuffPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel createPanel;
    private javax.swing.JButton desactivateButton;
    private javax.swing.JComboBox<String> destinationComboBox;
    private javax.swing.JLabel elementText;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JLabel nameText;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JLabel orderText;
    private javax.swing.JTabbedPane routesPanel;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton searchingButton;
    private javax.swing.JComboBox<String> searchingComboBox;
    private javax.swing.JLabel searchingText;
    private javax.swing.JSeparator separator;
    private javax.swing.JTable table;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel userText;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
