/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packagedelivery.FrontEnd.Management;

import java.sql.Connection;
import javax.swing.JOptionPane;
import packagedelivery.DBmanagers.DestinationDBManager;
import packagedelivery.DBmanagers.UserDBManager;
import packagedelivery.DummyClasses.Destination;
import packagedelivery.DummyClasses.User;

/**
 *
 * @author zofia
 */
public class UpdateDialog extends javax.swing.JDialog {
    private Connection connection;
    private User user;
    private Destination destination;
    private UserDBManager userInfo;
    private DestinationDBManager destinationInfo;
    private static final String UPDATE_USER_QUERY = "UPDATE User SET ";
    private static final String UPDATE_DESTINATION_QUERY = "UPDATE Destination SET ";
    /**
     * Creates new form updateDialog
     */
    public UpdateDialog(boolean modal, Connection connection, User user, Destination destination) {
        initComponents();
        this.connection = connection;
        this.user = user;
        this.destination = destination;
        userInfo = new UserDBManager(this.connection);
        destinationInfo = new DestinationDBManager(this.connection);
        this.setModal(modal);
        setEnabledStuff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        updatePanel = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        roleText = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        roleCombo = new javax.swing.JComboBox<>();
        passwordText = new javax.swing.JLabel();
        lastNameText = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        userText = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        creatStuffPanel = new javax.swing.JPanel();
        destinationField = new javax.swing.JTextField();
        feeField = new javax.swing.JTextField();
        nameText1 = new javax.swing.JLabel();
        updateDestinationButton = new javax.swing.JButton();
        userText1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        updatePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        roleText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        roleText.setForeground(new java.awt.Color(0, 51, 102));
        roleText.setText("Rol:");

        nameText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 51, 102));
        nameText.setText("Nombre:");

        roleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador", "Recepcionista" }));

        passwordText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        passwordText.setForeground(new java.awt.Color(0, 51, 102));
        passwordText.setText("Contraseña:");

        lastNameText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        lastNameText.setForeground(new java.awt.Color(0, 51, 102));
        lastNameText.setText("Apellido:");

        updateButton.setBackground(new java.awt.Color(153, 153, 153));
        updateButton.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(102, 102, 102));
        updateButton.setText("Actualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        userText.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        userText.setForeground(new java.awt.Color(0, 51, 102));
        userText.setText("Usuario:");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordText)
                            .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleText, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userField)
                            .addComponent(nameField)
                            .addComponent(lastNameField)
                            .addComponent(roleCombo, 0, 214, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addContainerGap())
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameText)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleText)
                    .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuarios", updatePanel);

        creatStuffPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameText1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        nameText1.setForeground(new java.awt.Color(0, 51, 102));
        nameText1.setText("Cuota de destino:");

        updateDestinationButton.setBackground(new java.awt.Color(153, 153, 153));
        updateDestinationButton.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        updateDestinationButton.setForeground(new java.awt.Color(102, 102, 102));
        updateDestinationButton.setText("Actualizar");
        updateDestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDestinationButtonActionPerformed(evt);
            }
        });

        userText1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        userText1.setForeground(new java.awt.Color(0, 51, 102));
        userText1.setText("Destino:");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ej: Mexico, Quetzaltenango, etc.");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 10)); // NOI18N
        jLabel3.setText("Ej: 55, 100.5, etc.");

        javax.swing.GroupLayout creatStuffPanelLayout = new javax.swing.GroupLayout(creatStuffPanel);
        creatStuffPanel.setLayout(creatStuffPanelLayout);
        creatStuffPanelLayout.setHorizontalGroup(
            creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatStuffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creatStuffPanelLayout.createSequentialGroup()
                        .addComponent(userText1)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(creatStuffPanelLayout.createSequentialGroup()
                        .addComponent(nameText1)
                        .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creatStuffPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(creatStuffPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(feeField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateDestinationButton))))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        creatStuffPanelLayout.setVerticalGroup(
            creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatStuffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText1)
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(creatStuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText1)
                    .addComponent(feeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addComponent(updateDestinationButton)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Destinos", creatStuffPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String query = getUserValues();       
        userInfo.updateInfoUser(query);
        JOptionPane.showMessageDialog(this, "Usuario actualizado...", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void updateDestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDestinationButtonActionPerformed
        // 
        destinationInfo.updateDestination(getDestinationValues());
        JOptionPane.showMessageDialog(this, "Destino actualizado...", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_updateDestinationButtonActionPerformed

    public void setEnabledStuff() {
        if(this.user != null) {
            disableDestinationStuff();
            setUserValues();
        } else if(this.destination != null) {
            setDestinationValues();
            disableUserStuff();
        }
    }
    
    public void disableDestinationStuff() {
        destinationField.disable();
        feeField.disable();
        updateDestinationButton.hide();
    }
    
    public void disableUserStuff() {
        userField.disable();
        nameField.disable();
        lastNameField.disable();
        passwordField.disable();
        roleCombo.disable();
        updateButton.hide();
    }
    
    public void setDestinationValues() {
        this.destinationField.setText(this.destination.getDestinationId());
        this.feeField.setText(String.valueOf(this.destination.getFee()));
    }
    
    public void setUserValues() {
        this.userField.setText(this.user.getUsername());
        this.userField.disable();
        this.nameField.setText(this.user.getName());
        this.lastNameField.setText(this.user.getLastName());
        this.passwordField.setText(this.user.getPassword());
        this.roleCombo.getModel().setSelectedItem(this.user.getRole());
    }
    
    public String getDestinationValues() {
        String destinationId = this.destination.getDestinationId();
        String newDestinationId = destinationField.getText();
        double fee = Double.valueOf(feeField.getText());
        String query = UPDATE_DESTINATION_QUERY + "IdDestination = '" + 
                newDestinationId + "', Fee = " + fee +" WHERE IdDestination = '" + destinationId + "';"; 
        return query;
    }
    
    public String getUserValues() {
        String username = this.user.getUsername();
        String name = nameField.getText();
        String lastName = lastNameField.getText();
        String password = passwordField.getText();
        String role = roleCombo.getModel().getSelectedItem().toString();
        String query = UPDATE_USER_QUERY + "Name = '" + name + "', LastName = '" + lastName 
               + "', Role = '" + role + "', Password = '" + password + "' WHERE Username = '" + username + "';";
        return query;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel creatStuffPanel;
    private javax.swing.JTextField destinationField;
    private javax.swing.JTextField feeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel nameText1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JComboBox<String> roleCombo;
    private javax.swing.JLabel roleText;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateDestinationButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userText;
    private javax.swing.JLabel userText1;
    // End of variables declaration//GEN-END:variables
}
